[meta]
name     = "ActiveCam"
author   = "XertroV"
category = "Developer"
version  = "0.1.0"

[script]
#__DEFINES__
module = "ActiveCam"
exports = ["AC_Exports.as"]
shared_exports = ["AC_ExportsShared.as"]
